from fpdf import FPDF
from datetime import datetime
from config import VERDICT_ELIGIBLE, VERDICT_NOT_ELIGIBLE, VERDICT_NEEDS_REVIEW


class TenderLensReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.cell(0, 8, "TenderLens — Tender Evaluation Report", align="R", new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

    def chapter_title(self, title):
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def section_title(self, title):
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def body_text(self, text):
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 5, text)
        self.ln(2)

    def verdict_badge(self, verdict):
        if verdict == VERDICT_ELIGIBLE:
            return "[ELIGIBLE]"
        elif verdict == VERDICT_NOT_ELIGIBLE:
            return "[NOT ELIGIBLE]"
        return "[NEEDS REVIEW]"


def _compute_overall(verdicts):
    mandatory = [v for v in verdicts if v.get("mandatory", True)]
    if any(v["verdict"] == VERDICT_NOT_ELIGIBLE for v in mandatory):
        return VERDICT_NOT_ELIGIBLE
    if any(v["verdict"] == VERDICT_NEEDS_REVIEW for v in mandatory):
        return VERDICT_NEEDS_REVIEW
    return VERDICT_ELIGIBLE


def generate_pdf_report(tender, criteria, bidders, all_verdicts,
                         overrides=None, audit_entries=None) -> bytes:
    """Generate a PDF evaluation report and return it as bytes."""
    pdf = TenderLensReport()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Cover Page ──
    pdf.add_page()
    pdf.ln(40)
    pdf.set_font("Helvetica", "B", 24)
    pdf.cell(0, 15, "TENDER EVALUATION REPORT", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    pdf.set_font("Helvetica", "", 14)
    pdf.cell(0, 10, f"Tender: {tender['name']}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%d %B %Y')}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 10, f"Criteria: {len(criteria)}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 10, f"Bidders: {len(bidders)}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(20)
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 8, "Generated by TenderLens — AI-Powered Eligibility Analysis",
             align="C", new_x="LMARGIN", new_y="NEXT")

    # ── Criteria Summary ──
    pdf.add_page()
    pdf.chapter_title("1. Eligibility Criteria")

    for c in criteria:
        mand = "Mandatory" if c.get("mandatory") else "Optional"
        pdf.section_title(f"{c['criterion_id']} ({c['category']}, {mand})")
        pdf.body_text(c["description"])
        if c.get("threshold"):
            pdf.body_text(f"Threshold: {c['threshold']}")

    # ── Consolidated Results ──
    pdf.add_page()
    pdf.chapter_title("2. Consolidated Results")

    bidder_names = list(dict.fromkeys(v["bidder_name"] for v in all_verdicts))

    # Summary table
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(80, 8, "Bidder", border=1)
    pdf.cell(30, 8, "Eligible", border=1, align="C")
    pdf.cell(30, 8, "Failed", border=1, align="C")
    pdf.cell(30, 8, "Review", border=1, align="C")
    pdf.cell(0, 8, "Overall", border=1, align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 9)
    for bname in bidder_names:
        bv = [v for v in all_verdicts if v["bidder_name"] == bname]
        overall = _compute_overall(bv)
        e_count = sum(1 for v in bv if v["verdict"] == VERDICT_ELIGIBLE)
        f_count = sum(1 for v in bv if v["verdict"] == VERDICT_NOT_ELIGIBLE)
        r_count = sum(1 for v in bv if v["verdict"] == VERDICT_NEEDS_REVIEW)

        name_display = bname[:35] + "..." if len(bname) > 35 else bname
        pdf.cell(80, 7, name_display, border=1)
        pdf.cell(30, 7, str(e_count), border=1, align="C")
        pdf.cell(30, 7, str(f_count), border=1, align="C")
        pdf.cell(30, 7, str(r_count), border=1, align="C")
        pdf.cell(0, 7, pdf.verdict_badge(overall), border=1, align="C",
                 new_x="LMARGIN", new_y="NEXT")

    # ── Per-Bidder Detail ──
    pdf.add_page()
    pdf.chapter_title("3. Detailed Evaluation")

    for bname in bidder_names:
        bv = [v for v in all_verdicts if v["bidder_name"] == bname]
        overall = _compute_overall(bv)

        pdf.section_title(f"{bname} — {pdf.verdict_badge(overall)}")

        for v in bv:
            badge = pdf.verdict_badge(v["verdict"])
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 6, f"{v['crit_code']} {badge} — {v.get('crit_desc', '')[:70]}",
                     new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            explanation = v.get("explanation", "No explanation.")
            pdf.multi_cell(0, 5, explanation[:300])
            pdf.ln(2)

        pdf.ln(4)

        if pdf.get_y() > 240:
            pdf.add_page()

    # ── Officer Overrides ──
    if overrides:
        pdf.add_page()
        pdf.chapter_title("4. Officer Overrides")
        for o in overrides:
            pdf.section_title(f"{o.get('bidder_name', '')} / {o.get('crit_code', '')}")
            pdf.body_text(
                f"Original: {o['original_verdict']} -> New: {o['new_verdict']}\n"
                f"Reason: {o['reason']}\n"
                f"Officer: {o.get('officer_name', 'N/A')} — {o['created_at']}"
            )

    # ── Audit Trail ──
    if audit_entries:
        pdf.add_page()
        pdf.chapter_title("5. Audit Trail")
        pdf.set_font("Helvetica", "", 8)
        for entry in audit_entries:
            line = f"[{entry['created_at']}] {entry['action']}"
            if entry.get("details"):
                line += f" — {entry['details']}"
            pdf.cell(0, 5, line[:120], new_x="LMARGIN", new_y="NEXT")

    return pdf.output()
